### ISSUE TITLE
Multiples Skywriters on one arduino board?

### ISSUE THREAD

**Issue by radames** [pimoroni/skywriter-hat#14]
I see that the I2C address for the skywriter it's hardcoded ```SW_ADDR 0x42```, would be possible assign different address to multiples Skywriter boards? therefore using only one Arduino to connect two or more skywriter boards?

**Comment by Gadgetoid** [comment]
Unfortunately this is impossible. You would have to, instead, use multiple i2c busses on the Arduino-end. With some suitable pull-up resistors, there's nothing stopping any two pins on an Arduino from being an i2c bus, and some little hackery with the library will fill in the rest.

**Comment by radames** [comment]
Great! Thanks for the answer!
