### ISSUE TITLE
Install script issues

### ISSUE THREAD

**Issue by jorisvervuurt** [pimoroni/skywriter-hat#16]
I noticed a few issues when trying to setup the Skywriter HAT:

When running the install script on a clean install of the latest Raspbian Jessie (Lite) image (on a Pi 3 in my case), it appears to be running fine the first time.

1. The install script appears to fail when trying to enable I2C.
Manually enabling I2C through `raspi-config` works.

2. When importing the `skywriter` Python library, a RPi.GPIO warning is shown regarding an already-in-use channel. Although this can be ignored using `GPIO.setwarnings(False)` as the library works fine, it's obviously not the best option.

3. When re-running the install script, it fails on trying to install `smbus`.

**Comment by Gadgetoid** [comment]
I've raised this issue against our install script repository where it should get the attention it deserves. Cheers! -> https://github.com/pimoroni/get/issues/64
