### ISSUE TITLE
deactivate auto-calibration

### ISSUE THREAD

**Issue by bigfoot69100** [pimoroni/skywriter-hat#22]
Hello,

Have you a method for deactivate the auto calibration on MGC3130 ?
I need detect a motionless body.

Thanks

Best regards

**Comment by Gadgetoid** [comment]
I've added this as part of: https://github.com/pimoroni/skywriter-hat/commit/1630317145e0ecaa9c3a153bf3a2018cb3c92b29

However I'm going to investigate making it optional if/when I get the time, and before releasing a new library version with this feature.
