### ISSUE TITLE
Skywriter hat cannot pick up on flicks - broken/not working?

### ISSUE THREAD

**Issue by nickdebCompApps** [pimoroni/skywriter-hat#27]
I have recently purchased a skywriter hat and have followed all directions on installing scripts and inserting hat into GPIO pins. When I run test.py, the script does not pickup on flicks, and once, say, I touch the board, the touch is registered but then it continues to print touch even when I am not touching it. When I press control + C to cancel the script running, it continues to print out test.py. I am wondering if this is a programming error or something on the hardware side.

**Comment by Gadgetoid** [comment]
Sorry for the delay responding- did you find a solution to this problem or manage to obtain a replacement from us?

**Comment by UnsignedArduino** [comment]
You have to touch a edge pad that does not have a grid on it and flick to the opposite pad that does not have a grid on ot
