### ISSUE TITLE
SW_CIRCLE_C(C)LOCKWISE gesture

### ISSUE THREAD

**Issue by Mynasru** [pimoroni/skywriter-hat#28]
I cannot get `SW_CIRCLE_CLOCKWISE` and `SW_CIRCLE_CCLOCKWISE` working, when are these supposed to be activated (what gesture) and are these triggered by `void gesture(unsigned char type)` or by another function?

Also the documentation on the Arduino library and examples is very scarce, it could use an update.

**Comment by Gadgetoid** [comment]
You're right- looks like I've neglected the Arduino library.

If I remember correctly it's the "onAirwheel" handler that you need.

It's a tricky gesture to get right, but basically involves spinning your finger around above the Skywriter in a clockwise or counter-clockwise direction.

**Comment by balamsoto** [comment]
having this into arduino / teensy arch can lead to more sales
Please update the lib and enable all the magic of this hardware
