### ISSUE TITLE
garbage gesture

### ISSUE THREAD

**Issue by Gh0stWires** [pimoroni/skywriter-hat#29]
So in the documentation it says there is a garbage gesture but the wording of how that gesture is performed doesn't really clarify how to actually make this gesture. I'm working on turning a pi into a gesture based hotkey machine and that one could prove useful for closing windows or opening a terminal. But for the life of me I can't figure out how it's performed. It's in the library but there are no code examples of it. Is it not finished? And I have just been waving like a mad man for no reason?

**Comment by Gadgetoid** [comment]
Sorry for the delay responding. The garbage gesture does exist, but it's so completely obtuse I've not made any effort to make it more apparent. If memory serves it basically involves sort of... pretending like you're picking something off the Skywriter and throwing it away.
