### ISSUE TITLE
How can I run this with Arduino UNO sir?

### ISSUE THREAD

**Issue by shafirayulia** [pimoroni/skywriter-hat#30]

**Comment by Gadgetoid** [comment]
Sorry for the - uh - year? late response (almost to the day, my word!). 

Arduino instructions are here - https://github.com/pimoroni/skywriter-hat/tree/master/arduino - but may be woefully out of date for the modern Arduino IDE. (It's been improved lots)

That said, I'm not sure there's anything much newer. The chip we use on Skywriter is an MGC3130 and there are libraries out there for it. For example - https://github.com/open-electronics/GestIC

**Comment by shafirayulia** [comment]
thankyou for your reply :)
